#!/bin/bash

SCRIPT_TARGET=$(./dev_scripts/script_target -t)
BUILD_FLAGS=$(./dev_scripts/script_target -b)
RUN_FLAGS=$(./dev_scripts/script_target -r)

bazel build ${BUILD_FLAGS} ${SCRIPT_TARGET} && lldb ./bazel-bin/${SCRIPT_TARGET} -- ${RUN_FLAGS}

